// src/vue/components/Calendar.vue
<template>
  <div :class="['kalendly-calendar', props.class]" :style="props.style">
    <div v-if="title || $slots.title" class="page--title">
      <slot name="title">
        <h1>{{ title }}</h1>
      </slot>
    </div>

    <div class="calendar--content">
      <div class="calendar--card">
        <h3 class="calendar--card--header">
          {{ viewModel.monthAndYearText }}
        </h3>

        <table class="calendar--table calendar--table--bordered">
          <thead>
            <tr>
              <th v-for="day in viewModel.days" :key="day">
                {{ day.slice(0, 3) }}
              </th>
            </tr>
          </thead>
          <tbody @click="handleDateClick">
            <tr
              v-for="(week, weekIndex) in viewModel.calendarDates"
              :key="weekIndex"
            >
              <td
                v-for="(calendarDate, dayIndex) in week"
                :key="`${weekIndex}-${dayIndex}`"
                :class="getCellClasses(calendarDate)"
              >
                {{ calendarDate?.date.getDate() || '' }}
              </td>
            </tr>
          </tbody>
        </table>

        <div
          v-if="viewModel.selectedDate"
          :class="['date-popup', viewModel.popupPositionClass]"
        >
          <button
            type="button"
            class="popup-close"
            aria-label="Close"
            @click="handleClosePopup"
          >
            ✕
          </button>
          <div class="schedule--wrapper">
            <div class="schedule--block">
              <h2 class="schedule--day">
                {{ viewModel.scheduleDay }}
              </h2>
            </div>

            <div v-if="viewModel.tasks.length > 0" class="event--wrapper">
              <ul>
                <li
                  v-for="event in viewModel.tasks"
                  :key="event.id || event.name"
                  class="event--item"
                  style="cursor: pointer"
                  @click="emit('event-click', event)"
                >
                  <slot name="event" :event="event">
                    {{ event.name }}
                  </slot>
                </li>
              </ul>
            </div>

            <div v-else class="no-events-message">
              <slot name="no-events"> No events scheduled for this day. </slot>
            </div>
          </div>
        </div>

        <div class="calendar--navigation--buttons">
          <button class="calendar--navigation--btn" @click="handlePrevious">
            Previous
          </button>
          <button class="calendar--navigation--btn" @click="handleNext">
            Next
          </button>
        </div>

        <form class="calendar--form--jump">
          <div class="calendar--lead">Jump To:</div>
          <div>
            <label class="calendar--form--jump--item">
              <select
                :value="viewModel.currentMonth"
                @change="handleMonthChange"
              >
                <option
                  v-for="(month, index) in viewModel.months"
                  :key="index"
                  :value="index"
                >
                  {{ month }}
                </option>
              </select>
            </label>
          </div>
          <div>
            <label class="calendar--form--jump--item">
              <select :value="viewModel.currentYear" @change="handleYearChange">
                <option
                  v-for="year in viewModel.years"
                  :key="year"
                  :value="year"
                >
                  {{ year }}
                </option>
              </select>
            </label>
          </div>
        </form>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, watch } from 'vue';
import {
  CalendarEngine,
  getCellClasses as getCoreCellClasses,
} from '../../core';
import type { VueCalendarProps } from '../types';
import type { CalendarEvent, CalendarDate } from '../../core/types';

const props = withDefaults(defineProps<VueCalendarProps>(), {
  events: () => [],
  weekStartsOn: 0,
  title: 'Event Schedule',
  class: '',
  style: () => ({}),
});

const emit = defineEmits<{
  'date-select': [date: Date];
  'event-click': [event: CalendarEvent];
  'month-change': [year: number, month: number];
}>();

const engine = new CalendarEngine({
  events: props.events,
  initialDate: props.initialDate,
  minYear: props.minYear,
  maxYear: props.maxYear,
  weekStartsOn: props.weekStartsOn,
});

const forceUpdate = ref(0);
const viewModel = computed(() => {
  // Trigger reactivity when forceUpdate changes
  void forceUpdate.value;
  return engine.getViewModel();
});

const actions = engine.getActions();

const getCellClasses = (calendarDate: CalendarDate | null) => {
  if (!calendarDate) return '';
  return getCoreCellClasses(calendarDate);
};

const handleDateClick = (event: Event) => {
  const td = (event.target as HTMLElement).closest('td');
  if (!td) return;

  const cellContent = td.textContent?.trim();
  if (!cellContent) return;

  const clickedDate = new Date(
    viewModel.value.currentYear,
    viewModel.value.currentMonth,
    parseInt(cellContent)
  );

  const dayIndex = td.parentNode
    ? Array.from(td.parentNode.children).indexOf(td)
    : 0;
  engine.handleDateClick(clickedDate, dayIndex);

  emit('date-select', clickedDate);
};

const handleNext = () => {
  actions.next();
  emit(
    'month-change',
    viewModel.value.currentYear,
    viewModel.value.currentMonth
  );
};

const handlePrevious = () => {
  actions.previous();
  emit(
    'month-change',
    viewModel.value.currentYear,
    viewModel.value.currentMonth
  );
};

const handleMonthChange = (event: Event) => {
  const select = event.target as HTMLSelectElement;
  const month = parseInt(select.value);
  actions.jump(viewModel.value.currentYear, month);
  emit('month-change', viewModel.value.currentYear, month);
};

const handleYearChange = (event: Event) => {
  const select = event.target as HTMLSelectElement;
  const year = parseInt(select.value);
  actions.jump(year, viewModel.value.currentMonth);
  emit('month-change', year, viewModel.value.currentMonth);
};

const handleClosePopup = () => {
  engine.clearSelection();
};

// Watch for prop changes
watch(
  () => props.events,
  newEvents => {
    engine.updateEvents(newEvents);
    forceUpdate.value++;
  },
  { deep: true }
);

// Subscribe to engine updates
let unsubscribe: (() => void) | null = null;

onMounted(() => {
  unsubscribe = engine.subscribe(() => {
    forceUpdate.value++;
  });
});

onUnmounted(() => {
  unsubscribe?.();
  engine.destroy();
});
</script>

// src/react/components/Calendar.tsx
import React, { useEffect, useState, useCallback, useMemo } from 'react';
import { CalendarEngine, getCellClasses } from '../../core';
import { CalendarComponentProps } from '../types';
import { DatePopup } from './DatePopup';

export const Calendar: React.FC<CalendarComponentProps> = ({
  events,
  initialDate,
  minYear,
  maxYear,
  weekStartsOn = 0,
  onDateSelect,
  onEventClick,
  onMonthChange,
  className = '',
  style,
  renderEvent,
  renderNoEvents,
  title = 'Event Schedule',
}) => {
  const engine = useMemo(
    () =>
      new CalendarEngine({
        events,
        initialDate,
        minYear,
        maxYear,
        weekStartsOn,
      }),
    [events, initialDate, minYear, maxYear, weekStartsOn]
  );

  const [, forceUpdate] = useState({});
  const rerender = useCallback(() => forceUpdate({}), []);

  useEffect(() => {
    const unsubscribe = engine.subscribe(rerender);
    return unsubscribe;
  }, [engine, rerender]);

  useEffect(() => {
    engine.updateEvents(events);
  }, [engine, events]);

  useEffect(() => {
    return () => {
      engine.destroy();
    };
  }, [engine]);

  const viewModel = engine.getViewModel();
  const actions = engine.getActions();
  const { selectedDate, tasks } = viewModel;

  const handleDateClick = (
    event: React.MouseEvent<HTMLTableSectionElement>
  ) => {
    const td = (event.target as HTMLElement).closest('td');
    if (!td) return;

    const cellContent = td.textContent?.trim();
    if (!cellContent) return;

    const clickedDate = new Date(
      viewModel.currentYear,
      viewModel.currentMonth,
      parseInt(cellContent)
    );

    const dayIndex = td.parentNode
      ? Array.from(td.parentNode.children).indexOf(td)
      : 0;
    engine.handleDateClick(clickedDate, dayIndex);

    onDateSelect?.(clickedDate);
  };

  const handleMonthChange = () => {
    onMonthChange?.(viewModel.currentYear, viewModel.currentMonth);
  };

  const handleYearChange = (event: React.ChangeEvent<HTMLSelectElement>) => {
    const year = parseInt(event.target.value);
    actions.jump(year, viewModel.currentMonth);
    handleMonthChange();
  };

  const handleMonthSelectChange = (
    event: React.ChangeEvent<HTMLSelectElement>
  ) => {
    const month = parseInt(event.target.value);
    actions.jump(viewModel.currentYear, month);
    handleMonthChange();
  };

  const handleNext = () => {
    actions.next();
    handleMonthChange();
  };

  const handlePrevious = () => {
    actions.previous();
    handleMonthChange();
  };

  return (
    <div className={`kalendly-calendar ${className}`} style={style}>
      {title && (
        <div className="page--title">
          <h1>{title}</h1>
        </div>
      )}

      <div className="calendar--content">
        <div className="calendar--card">
          <h3 className="calendar--card--header">
            {viewModel.monthAndYearText}
          </h3>

          <table className="calendar--table calendar--table--bordered">
            <thead>
              <tr>
                {viewModel.days.map(day => (
                  <th key={day}>{day.slice(0, 3)}</th>
                ))}
              </tr>
            </thead>
            <tbody onClick={handleDateClick}>
              {viewModel.calendarDates.map((week, weekIndex) => (
                <tr key={weekIndex}>
                  {week.map((calendarDate, dayIndex) => {
                    const cellClasses = getCellClasses(calendarDate);
                    return (
                      <td
                        key={`${weekIndex}-${dayIndex}`}
                        className={cellClasses.join(' ')}
                      >
                        {calendarDate?.date.getDate() || ''}
                      </td>
                    );
                  })}
                </tr>
              ))}
            </tbody>
          </table>

          <div className="calendar--navigation--buttons">
            <button
              className="calendar--navigation--btn"
              onClick={handlePrevious}
            >
              Previous
            </button>
            <button className="calendar--navigation--btn" onClick={handleNext}>
              Next
            </button>
          </div>

          <form className="calendar--form--jump">
            <div className="calendar--lead">Jump To:</div>
            <div>
              <label className="calendar--form--jump--item">
                <select
                  value={viewModel.currentMonth}
                  onChange={handleMonthSelectChange}
                  aria-label="Select month"
                >
                  {viewModel.months.map((month, index) => (
                    <option key={index} value={index}>
                      {month}
                    </option>
                  ))}
                </select>
              </label>
            </div>
            <div>
              <label className="calendar--form--jump--item">
                <select
                  value={viewModel.currentYear}
                  onChange={handleYearChange}
                  aria-label="Select year"
                >
                  {viewModel.years.map(year => (
                    <option key={year} value={year}>
                      {year}
                    </option>
                  ))}
                </select>
              </label>
            </div>
          </form>

          <DatePopup
            isVisible={!!selectedDate}
            selectedDate={selectedDate}
            events={tasks}
            scheduleDay={viewModel.scheduleDay}
            popupPositionClass={viewModel.popupPositionClass}
            onClose={() => engine.clearSelection()}
            onEventClick={onEventClick}
            renderEvent={renderEvent}
            renderNoEvents={renderNoEvents}
          />
        </div>
      </div>
    </div>
  );
};
