// src/vue/components/Calendar.vue
<template>
  <div :class="['kalendly-calendar', props.class]" :style="props.style">
    <div v-if="title || $slots.title" class="page--title">
      <slot name="title">
        <h1>{{ title }}</h1>
      </slot>
    </div>

    <div class="calendar--content">
      <div class="calendar--card">
        <h3 class="calendar--card--header">
          {{ viewModel.monthAndYearText }}
        </h3>

        <table class="calendar--table calendar--table--bordered">
          <thead>
            <tr>
              <th v-for="day in viewModel.days" :key="day">
                {{ day.slice(0, 3) }}
              </th>
            </tr>
          </thead>
          <tbody @click="handleDateClick">
            <tr
              v-for="(week, weekIndex) in viewModel.calendarDates"
              :key="weekIndex"
            >
              <td
                v-for="(calendarDate, dayIndex) in week"
                :key="`${weekIndex}-${dayIndex}`"
                :class="getCellClasses(calendarDate)"
              >
                {{ calendarDate?.date.getDate() || '' }}
              </td>
            </tr>
          </tbody>
        </table>

        <div
          v-if="viewModel.selectedDate"
          :class="['date-popup', viewModel.popupPositionClass]"
        >
          <button
            type="button"
            class="popup-close"
            aria-label="Close"
            @click="handleClosePopup"
          >
            ✕
          </button>
          <div class="schedule--wrapper">
            <div class="schedule--block">
              <h2 class="schedule--day">
                {{ viewModel.scheduleDay }}
              </h2>
            </div>

            <div v-if="viewModel.tasks.length > 0" class="event--wrapper">
              <ul>
                <li
                  v-for="event in viewModel.tasks"
                  :key="event.id || event.name"
                  class="event--item"
                  style="cursor: pointer"
                  @click="emit('event-click', event)"
                >
                  <slot name="event" :event="event">
                    {{ event.name }}
                  </slot>
                </li>
              </ul>
            </div>

            <div v-else class="no-events-message">
              <slot name="no-events"> No events scheduled for this day. </slot>
            </div>
          </div>
        </div>

        <div class="calendar--navigation--buttons">
          <button class="calendar--navigation--btn" @click="handlePrevious">
            Previous
          </button>
          <button class="calendar--navigation--btn" @click="handleNext">
            Next
          </button>
        </div>

        <form class="calendar--form--jump">
          <div class="calendar--lead">Jump To:</div>
          <div>
            <label class="calendar--form--jump--item">
              <select
                :value="viewModel.currentMonth"
                @change="handleMonthChange"
              >
                <option
                  v-for="(month, index) in viewModel.months"
                  :key="index"
                  :value="index"
                >
                  {{ month }}
                </option>
              </select>
            </label>
          </div>
          <div>
            <label class="calendar--form--jump--item">
              <select :value="viewModel.currentYear" @change="handleYearChange">
                <option
                  v-for="year in viewModel.years"
                  :key="year"
                  :value="year"
                >
                  {{ year }}
                </option>
              </select>
            </label>
          </div>
        </form>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, watch } from 'vue';
import {
  CalendarEngine,
  getCellClasses as getCoreCellClasses,
} from '../../core';
import type { VueCalendarProps } from '../types';
import type { CalendarEvent, CalendarDate } from '../../core/types';

const props = withDefaults(defineProps<VueCalendarProps>(), {
  events: () => [],
  weekStartsOn: 0,
  title: 'Event Schedule',
  class: '',
  style: () => ({}),
});

const emit = defineEmits<{
  'date-select': [date: Date];
  'event-click': [event: CalendarEvent];
  'month-change': [year: number, month: number];
}>();

const engine = new CalendarEngine({
  events: props.events,
  initialDate: props.initialDate,
  minYear: props.minYear,
  maxYear: props.maxYear,
  weekStartsOn: props.weekStartsOn,
});

const forceUpdate = ref(0);
const viewModel = computed(() => {
  // Trigger reactivity when forceUpdate changes
  void forceUpdate.value;
  return engine.getViewModel();
});

const actions = engine.getActions();

const getCellClasses = (calendarDate: CalendarDate | null) => {
  if (!calendarDate) return '';
  return getCoreCellClasses(calendarDate);
};

const handleDateClick = (event: Event) => {
  const td = (event.target as HTMLElement).closest('td');
  if (!td) return;

  const cellContent = td.textContent?.trim();
  if (!cellContent) return;

  const clickedDate = new Date(
    viewModel.value.currentYear,
    viewModel.value.currentMonth,
    parseInt(cellContent)
  );

  const dayIndex = td.parentNode
    ? Array.from(td.parentNode.children).indexOf(td)
    : 0;
  engine.handleDateClick(clickedDate, dayIndex);

  emit('date-select', clickedDate);
};

const handleNext = () => {
  actions.next();
  emit(
    'month-change',
    viewModel.value.currentYear,
    viewModel.value.currentMonth
  );
};

const handlePrevious = () => {
  actions.previous();
  emit(
    'month-change',
    viewModel.value.currentYear,
    viewModel.value.currentMonth
  );
};

const handleMonthChange = (event: Event) => {
  const select = event.target as HTMLSelectElement;
  const month = parseInt(select.value);
  actions.jump(viewModel.value.currentYear, month);
  emit('month-change', viewModel.value.currentYear, month);
};

const handleYearChange = (event: Event) => {
  const select = event.target as HTMLSelectElement;
  const year = parseInt(select.value);
  actions.jump(year, viewModel.value.currentMonth);
  emit('month-change', year, viewModel.value.currentMonth);
};

const handleClosePopup = () => {
  engine.clearSelection();
};

// Watch for prop changes
watch(
  () => props.events,
  newEvents => {
    engine.updateEvents(newEvents);
    forceUpdate.value++;
  },
  { deep: true }
);

// Subscribe to engine updates
let unsubscribe: (() => void) | null = null;

onMounted(() => {
  unsubscribe = engine.subscribe(() => {
    forceUpdate.value++;
  });
});

onUnmounted(() => {
  unsubscribe?.();
  engine.destroy();
});
</script>

// src/react-native/components/Calendar.tsx
import React, { useEffect, useState, useCallback, useMemo } from 'react';
import { View, Text, TouchableOpacity, ScrollView, Alert } from 'react-native';
import { CalendarEngine, getCellClasses } from '../../core';
import { CalendarComponentProps, SelectProps } from '../types';
import { DatePopup } from './DatePopup';
import { calendarStyles } from '../../styles/react-native-styles';

// Simple Select component for React Native
const Select: React.FC<SelectProps> = ({
  options,
  selectedValue,
  onValueChange,
  style,
  textStyle,
}) => {
  const selectedOption = options.find(opt => opt.value === selectedValue);

  const showPicker = () => {
    Alert.alert(
      'Select Option',
      '',
      options.map(option => ({
        text: option.label,
        onPress: () => onValueChange(option.value),
      }))
    );
  };

  return (
    <TouchableOpacity
      style={[calendarStyles.jumpSelect, style]}
      onPress={showPicker}
    >
      <Text style={[calendarStyles.jumpSelectText, textStyle]}>
        {selectedOption?.label}
      </Text>
    </TouchableOpacity>
  );
};

export const Calendar: React.FC<CalendarComponentProps> = ({
  events,
  initialDate,
  minYear,
  maxYear,
  weekStartsOn = 0,
  onDateSelect,
  onEventClick,
  onMonthChange,
  style,
  containerStyle,
  headerStyle,
  headerTextStyle,
  cellStyle,
  cellTextStyle,
  renderEvent,
  renderNoEvents,
  title = 'Event Schedule',
  showCloseButton = true,
}) => {
  const engine = useMemo(
    () =>
      new CalendarEngine({
        events,
        initialDate,
        minYear,
        maxYear,
        weekStartsOn,
      }),
    []
  );

  const [, forceUpdate] = useState({});
  const rerender = useCallback(() => forceUpdate({}), []);

  useEffect(() => {
    const unsubscribe = engine.subscribe(rerender);
    return unsubscribe;
  }, [engine, rerender]);

  useEffect(() => {
    engine.updateEvents(events);
  }, [engine, events]);

  const viewModel = engine.getViewModel();
  const actions = engine.getActions();
  const { selectedDate, tasks } = viewModel;

  const handleDatePress = (date: Date, dayIndex: number) => {
    engine.handleDateClick(date, dayIndex);
    onDateSelect?.(date);
  };

  const handleNext = () => {
    actions.next();
    onMonthChange?.(viewModel.currentYear, viewModel.currentMonth);
  };

  const handlePrevious = () => {
    actions.previous();
    onMonthChange?.(viewModel.currentYear, viewModel.currentMonth);
  };

  const handleMonthChange = (month: number) => {
    actions.jump(viewModel.currentYear, month);
    onMonthChange?.(viewModel.currentYear, month);
  };

  const handleYearChange = (year: number) => {
    actions.jump(year, viewModel.currentMonth);
    onMonthChange?.(year, viewModel.currentMonth);
  };

  const closePopup = () => {
    engine.clearSelection();
  };

  const monthOptions = viewModel.months.map((month, index) => ({
    label: month,
    value: index,
  }));

  const yearOptions = viewModel.years.map(year => ({
    label: year.toString(),
    value: year,
  }));

  return (
    <ScrollView style={[calendarStyles.container, containerStyle]}>
      {title && (
        <View style={calendarStyles.titleContainer}>
          <Text style={calendarStyles.title}>{title}</Text>
        </View>
      )}

      <View style={[calendarStyles.contentContainer, style]}>
        <View style={calendarStyles.card}>
          <View style={[calendarStyles.cardHeader, headerStyle]}>
            <Text style={[calendarStyles.cardHeaderText, headerTextStyle]}>
              {viewModel.monthAndYearText}
            </Text>
          </View>

          <View style={calendarStyles.table}>
            {/* Table Header */}
            <View style={calendarStyles.tableHeader}>
              {viewModel.days.map(day => (
                <View key={day} style={calendarStyles.tableHeaderCell}>
                  <Text style={calendarStyles.tableHeaderText}>
                    {day.slice(0, 3)}
                  </Text>
                </View>
              ))}
            </View>

            {/* Calendar Rows */}
            {viewModel.calendarDates.map((week, weekIndex) => (
              <View key={weekIndex} style={calendarStyles.tableRow}>
                {week.map((calendarDate, dayIndex) => {
                  const cellClasses = getCellClasses(calendarDate);
                  const isToday = cellClasses.includes(
                    'schedule--current--exam'
                  );
                  const hasEvents = cellClasses.includes('has--event');

                  return (
                    <TouchableOpacity
                      key={`${weekIndex}-${dayIndex}`}
                      style={[
                        calendarStyles.tableCell,
                        cellStyle,
                        isToday && calendarStyles.cellToday,
                        hasEvents && calendarStyles.cellWithEvents,
                      ]}
                      onPress={() => {
                        if (calendarDate) {
                          handleDatePress(calendarDate.date, dayIndex);
                        }
                      }}
                      disabled={!calendarDate}
                    >
                      {calendarDate && (
                        <>
                          <Text
                            style={[
                              calendarStyles.tableCellText,
                              cellTextStyle,
                              isToday && calendarStyles.cellTodayText,
                            ]}
                          >
                            {calendarDate.date.getDate()}
                          </Text>
                          {hasEvents && (
                            <View style={calendarStyles.eventIndicator} />
                          )}
                        </>
                      )}
                    </TouchableOpacity>
                  );
                })}
              </View>
            ))}
          </View>

          {/* Navigation Buttons */}
          <View style={calendarStyles.navigationContainer}>
            <TouchableOpacity
              style={calendarStyles.navigationButton}
              onPress={handlePrevious}
            >
              <Text style={calendarStyles.navigationButtonText}>Previous</Text>
            </TouchableOpacity>
            <TouchableOpacity
              style={calendarStyles.navigationButton}
              onPress={handleNext}
            >
              <Text style={calendarStyles.navigationButtonText}>Next</Text>
            </TouchableOpacity>
          </View>

          {/* Jump Form */}
          <View style={calendarStyles.jumpForm}>
            <Text style={calendarStyles.jumpLabel}>Jump To:</Text>
            <Select
              options={monthOptions}
              selectedValue={viewModel.currentMonth}
              onValueChange={handleMonthChange}
            />
            <Select
              options={yearOptions}
              selectedValue={viewModel.currentYear}
              onValueChange={handleYearChange}
            />
          </View>
        </View>
      </View>

      <DatePopup
        visible={!!selectedDate}
        selectedDate={selectedDate}
        events={tasks}
        scheduleDay={viewModel.scheduleDay}
        onClose={closePopup}
        renderEvent={renderEvent}
        renderNoEvents={renderNoEvents}
        showCloseButton={showCloseButton}
      />
    </ScrollView>
  );
};
